#:schema https://numm.dev/wrangler.schema.json
name = "tuanphamcyber"
compatibility_date = "2024-04-12"
pages_build_output_dir = "./dist"

[assets]
directory = "./dist"
binding = "ASSETS_BINDING"
# Lưu ý: Không đặt tên là ASSETS vì đây là từ khóa bảo mật của Cloudflare
